# Generated by Django 3.1.1 on 2020-10-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=0, verbose_name='Оцінка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uakinotv.film', verbose_name='фільм')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
