# Generated by Django 3.1.1 on 2020-10-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0002_auto_20201012_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голосування'},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='film',
        ),
        migrations.CreateModel(
            name='FilmVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uakinotv.film', verbose_name='фільм')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uakinotv.vote', verbose_name='фільм')),
            ],
            options={
                'verbose_name': 'Оцінювання',
                'verbose_name_plural': 'Оцінювання',
            },
        ),
    ]
