# Generated by Django 3.1.1 on 2020-10-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0003_auto_20201012_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmvotes',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uakinotv.vote', verbose_name='Оцінка'),
        ),
    ]
