# Generated by Django 3.1.1 on 2020-10-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0004_auto_20201013_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorpr',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actorpr',
            name='image',
        ),
    ]
