# Generated by Django 3.1.1 on 2020-10-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0005_auto_20201013_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Mark',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
