# Generated by Django 3.1.1 on 2020-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0006_auto_20201015_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
