# Generated by Django 3.1.1 on 2020-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0007_film_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='votes',
        ),
        migrations.AddField(
            model_name='mark',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
