# Generated by Django 3.1.1 on 2020-10-19 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0008_auto_20201015_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=datetime.date.today, verbose_name='Дата виходу')),
            ],
        ),
    ]
