# Generated by Django 3.1.1 on 2020-10-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0009_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
    ]
