# Generated by Django 3.1.1 on 2020-10-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uakinotv', '0010_remove_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='uakinotv.year', verbose_name='Дата виходу'),
            preserve_default=False,
        ),
    ]
